# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'University Parking' do
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
  # Pods for University Parking

  target 'University ParkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'University ParkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
